language: go

go:
    - "1.x"
    - "1.8"
    - "1.10.x"
    - master

before_install:
    - go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/mattn/goveralls

script:
    - go test -v ./...
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci 
